/*
Author: Jmaster[SHG]
created for SpearheadGaming @ spearheadgaming.net
*/


//config for arsenal,use weapon/item classnames

_weapons = [
"RHS_WEAP_M4",
"RHS_WEAP_M4_CARRYHANDLE_PMAG",
"RHS_WEAP_M4_CARRYHANDLE",
"RHS_WEAP_M4A1",
"RHS_WEAP_M4A1_CARRYHANDLE",
"RHS_WEAP_M4A1_CARRYHANDLE_PMAG",
"RHS_WEAP_M4_GRIP",
"RHS_WEAP_M4_GRIP2",
"RHS_WEAP_M4_BIPOD",
"RHS_WEAP_M4A1_GRIP",
"RHS_WEAP_M4A1_CARRYHANDLE_GRIP",
"RHS_WEAP_M4A1_GRIP2",
"RHS_WEAP_M4A1_CARRYHANDLE_GRIP2",
"RHS_WEAP_M4A1_BIPOD",
"RHS_WEAP_M4A1_CARRYHANDLE_BIPOD",
"RHS_WEAP_M16A4",
"RHS_WEAP_M16A4_CARRYHANDLE",
"RHS_WEAP_M16A4_CARRYHANDLE_PMAG",
"RHS_WEAP_M16A4_BIPOD",
"RHS_WEAP_M16A4_CARRYHANDLE_BIPOD",
"RHS_WEAP_M16A4_GRIP",
"RHS_WEAP_M16A4_CARRYHANDLE_GRIP",
"RHS_WEAP_M16A4_CARRYHANDLE_GRIP_PMAG",
"RHS_WEAP_M16A4_CARRYHANDLE_M203",
"RHS_WEAP_M4_M320",
"RHS_WEAP_M4A1_M320",
"RHS_WEAP_M4_M203",
"RHS_WEAP_M4_M203S",
"RHS_WEAP_M4A1_M203",
"RHS_WEAP_M4A1_M203S",
"RHS_WEAP_M4A1_M203S_WD",
"RHS_WEAP_M4A1_M203S_D",
"RHS_WEAP_M4A1_M203S_SA",
"RHS_WEAP_M4A1_CARRYHANDLE_M203",
"RHS_WEAP_M4A1_CARRYHANDLE_M203S",
"RHS_WEAP_M249_PIP_S",
"RHS_WEAP_M249_PIP",
"RHS_WEAP_M249_PIP_L",
"rhs_weap_m24sws",
"rhs_weap_m24sws_blk",
"RHS_WEAP_M136_HEDP",
"RHS_WEAP_M136_HP",
"RHS_WEAP_M136",
"RHS_WEAP_M16A4_GRIP_ACOG3",
"RHS_WEAP_M16A4_GRIP_COMPM4",
"RHS_M4A1_M320_ACOG3",
"RHS_M4A1_M320_ACOG2",
"RHS_M4A1_M320_ACOG",
"RHS_M4A1_M320_COMPM4",
"RHS_WEAP_M4A1_GRIP2_ACOG2",
"RHS_M4A1_GRIP_ACOG3",
"RHS_M4A1_GRIP_ACOG2",
"RHS_M4A1_GRIP_ACOG",
"RHS_M4A1_ACOG3",
"RHS_M4A1_ACOG2",
"RHS_M4A1_ACOG",
"RHS_M4A1_COMPM4",
"RHS_M4A1_BIPOD_ACOG_USMC",
"RHS_M4A1_GRIP_COMPM4",
"RHS_M4_M320_ACOG3",
"RHS_M4_M320_ACOG2",
"RHS_M4_M320_ACOG",
"RHS_M4_M320_COMPM4",
"RHS_M4_GRIP_ACOG3",
"RHS_M4_GRIP_ACOG2",
"RHS_M4_GRIP_ACOG",
"RHS_M4_GRIP_COMPM4",
"RHS_M4_ACOG3",
"RHS_M4_ACOG2",
"RHS_M4_ACOG",
"RHS_M4_COMPM4",
"RHSUSF_WEAP_GLOCK17G4",
"RHSUSF_WEAP_M1911A1",
"RHS_M4A1_EOTECH",
"RHS_M4_M203_ACOG_USMC",
"RHS_M4_ACOG2_USMC",
"RHS_M4_ACOG_USMC",
"RHS_M4A1_ACOG_USMC",
"RHS_M4A1_ACOG2_USMC",
"RHS_M4A1_ACOG3_USMC",
"RHS_M4A1_GRIP_EOTECH",
"RHS_M4A1_GRIP_ACOG_USMC",
"RHS_M4A1_GRIP_ACOG2_USMC",
"RHS_M4A1_GRIP_ACOG3_USMC",
"RHS_M4A1_GRIP_ACOG2_USMC_SUP",
"RHS_M4A1_M203_ACOG_USMC",
"RHS_WEAP_M16A4_ACOG_USMC",
"RHS_WEAP_M16A4_M203_ACOG_USMC",
"RHS_WEAP_M16A4_GRIP_ACOG_USMC",
"RHS_WEAP_M16A4_GRIP_ACOG2_USMC",
"RHS_WEAP_M16A4_GRIP_ACOG3_USMC",
"RHS_WEAP_M39",
"RHS_WEAP_M320",
"RHS_WEAP_M590_5RD",
"RHS_WEAP_M590_8RD",
"rhs_weap_m27iar",
"rhs_weap_sr25_wd",
"rhs_weap_sr25",

"rhsusf_weap_m9",
"ACE_Vector",
"rhsusf_ANPVS_14",
"rhsusf_ANPVS_15",
"Binocular",
"rhs_weap_fgm148",

"rhs_weap_sr25_d"
];
_items = [ 
"rhs_googles_yellow",
"rhs_googles_clear",
"G_Combat",
"ACRE_PRC117F",
"LEUPOLD_MK4",
"LERCA_1200_TAN",
"LERCA_1200_BLACK",
"RHSUSF_ACC_LEUPOLDMK4_2",
"RHSUSF_ACC_COMPM4",
"RHSUSF_ACC_EOTECH_552",
"RHSUSF_ACC_ELCAN",
"RHSUSF_ACC_ACOG",
"RHSUSF_ACC_ACOG_WD",
"RHSUSF_ACC_ACOG_D",
"RHSUSF_ACC_ACOG2",
"RHSUSF_ACC_ACOG3",
"RHSUSF_ACC_ACOG_USMC",
"RHSUSF_ACC_ACOG2_USMC",
"RHSUSF_ACC_ACOG3_USMC",
"RHSUSF_ACC_EOTECH",
"RHSUSF_ACC_ANPEQ15A",
"RHSUSF_ACC_ANPEQ15",
"RHSUSF_ACC_ANPEQ15SIDE",
"RHSUSF_ACC_ANPEQ15_LIGHT",
"ACRE_PRC148",
"ACRE_PRC343",
"ItemcTab",
 "ItemAndroid",
 "ItemcTabHCam",
 "ItemMicroDAGR",
"ItemMap",
"ACE_MapTools",
"ACE_microDAGR",
"ItemWatch",
"ACE_wirecutter",
"ACE_bodyBag",
"ACE_CableTie",
"ACE_NVG_Gen2",
"ItemCompass",
"rhsusf_spc_mg",
"ACE_Flashlight_XL50",
"rhsusf_spc_rifleman",
"ACE_RangeTable",
"ACE_microDAGR",
"rhsusf_spc_iar",
"rhsusf_spc_corpsman",
"rhsusf_spc_light",
"rhsusf_spc_teamleader",
"rhsusf_spc_squadleader",
"ACE_EarPlugs"
];
_magazines = [ 
"RHSUSF_M112_AMMO",
"RHSUSF_M112X4_AMMO",
"RHSUSF_MINE_M19_AMMO",
"RHSUSF_40MM_HE",
"RHSUSF_40MM_PRACTICE",
"RHSUSF_40MM_WHITE",
"RHSUSF_40MM_RED",
"RHSUSF_40MM_GREEN",
"RHS_AMMO_M67",
"RHS_AMMO_M69",
"RHS_AMMO_AN_M14_TH3",
"RHS_AMMO_M18_GREEN",
"RHS_AMMO_M18_PURPLE",
"RHS_AMMO_M18_RED",
"RHS_AMMO_M18_YELLOW",
"RHS_MAG_M18_SMOKE_BASE",
"mini_Grenade",
"SmokeShellRed",
"SmokeShellGreen",
"SmokeShellYellow",
"SmokeShellPurple",
"SmokeShellBlue",
"SmokeShellOrange",
"Chemlight_green",
"rhs_LaserMag",
"Chemlight_red",
"Chemlight_yellow",
"ACE_HandFlare_Green",
"ACE_HandFlare_Red",
"ACE_HandFlare_White",
"ACE_HandFlare_Yellow"
];
_backpacks = [
"rhsusf_assault_eagleaiii_coy",
"rhsusf_falconii",
"tf_anprc155",
"B_rhsusf_BACKPACK",
"B_Kitbag_cbr",
"B_AssaultPack_cbr"
];





//------------------------DO NOT TOUCH----------------------------------------------------
_crate = _this;
_crate AddAction ["<t color=""#4DB0E2"">" +"Light Infantry Crate", "","",6];


[_crate,_weapons,{true}] call BIS_fnc_addVirtualWeaponCargo;
[_crate,_items,{true}] call BIS_fnc_addVirtualItemCargo;
[_crate,_magazines,{true}] call BIS_fnc_addVirtualMagazineCargo;
[_crate,_backpacks,{true}] call BIS_fnc_addVirtualBackpackCargo;