/*
Author: Jmaster[SHG]
created for SpearheadGaming @ spearheadgaming.net
*/


//config for arsenal,use weapon/item classnames

_weapons = ["rhs_weap_mk18",
"rhs_weap_mk18_KAC",
"rhs_weap_mk18_grip2",
"rhs_weap_mk18_grip2_KAC",
"rhs_weap_mk18_m320",
"rhs_weap_m240B",
"rhs_weap_m240G",
"rhs_weap_m240B_CAP",
"rhs_weap_m14ebrri",
"rhs_weap_sr25",
"rhs_weap_sr25_ec",
"rhs_weap_m110",
"rhs_weap_M107",
"rhs_weap_M590_5RD",
"rhs_weap_M590_8RD",
"rhs_weap_m32",
"rhs_weap_M136",
"rhs_weap_M136_hedp",
"rhs_weap_M136_hp",
"rhs_weap_m14ebrri_leu",
"rhs_weap_XM2010_d_leu",
"rhs_weap_XM2010_wd_leu",
"rhs_weap_m240b_elcan",
"rhs_weap_m240b_usmc",
"ACE_Flashlight_XL50",
"rhs_weap_m249_pip_usmc",
"rhs_weap_sr25_usmc",
"rhs_weap_sr25_sup_usmc",
"rhs_weap_sr25_sup_marsoc",
"rhs_weap_m32_usmc",
"RHS_SigP229",
"RHS_BerettaM9",
"RHS_M1911",
"RHS_HK416s",
"rhs_weap_M320",
"rhs_weap_m249_pip_L",
"rhs_weap_fim92",
"rhs_weap_XM2010",
"rhs_weap_m249_pip",
"rhs_weap_m249_pip_L_vfg",
"rhsusf_weap_m9",
"rhs_weap_m249_pip_S",
"rhs_weap_smaw_green",
"RHS_HK417s"];

_items = [ //includes uniforms
"ACE_NVG_Gen2",
 "G_Tactical_Black",
 "Binocular",
 "ACE_wirecutter",
 "ACE_NVG_Gen1",
 "ItemcTab",
 "ItemAndroid",
 "ItemcTabHCam",
 "ACE_Flashlight_MX991",
 "ItemMicroDAGR",
 "ACE_UAVBattery",
 "ACE_morphine",
 "G_Combat",
 "ACE_Vector",
 "ACE_plasmaIV",
 "G_Bandanna_tan",
 "rhs_googles_black",
 "ACE_Altimeter",
 "ACE_salineIV",
 "B_UavTerminal",
 "ACE_DeadManSwitch",
 "ACE_CableTie",
 "G_Diving",
 "rhsusf_bowman_cap",
 "NVGoggles_INDEP",
 "rhs_tr8_periscope",
 "ACE_NVG_Wide",
 "rhs_googles_yellow",
 "rhsusf_opscore_02",
 "rhsusf_opscore_01",
 "ItemGPS",
 "ACE_tourniquet",
 "rhsusf_ANPVS_15",
 "rhsusf_mich_bare_norotos_headset",
 "tf_anprc148jem",
 "rhsusf_ANPVS_14",
 "ACE_DefusalKit",
 "RHSUSF_ACC_COMPM4",
"RHSUSF_ACC_EOTECH_552",
"RHSUSF_ACC_ELCAN",
"RHSUSF_ACC_ACOG",
"RHSUSF_ACC_ACOG_WD",
"RHSUSF_ACC_ACOG_D",
"RHSUSF_ACC_ACOG2",
"RHSUSF_ACC_ACOG3",
"RHSUSF_ACC_ACOG_USMC",
"RHSUSF_ACC_ACOG2_USMC",
"RHSUSF_ACC_ACOG3_USMC",
"RHSUSF_ACC_EOTECH",
"RHSUSF_ACC_ANPEQ15A",
"RHSUSF_ACC_ANPEQ15",
"RHSUSF_ACC_ANPEQ15SIDE",
"RHSUSF_ACC_ANPEQ15_LIGHT",
"LEUPOLD_MK4",
"LERCA_1200_TAN",
"LERCA_1200_BLACK",
"RHSUSF_ACC_LEUPOLDMK4_2",
 "Medikit",
 "ACE_quikclot",
 "rhsusf_mich_bare_norotos_alt_headset",
 "ACE_salineIV_250",
 "ACE_plasmaIV_500",
 "ACE_bodyBag",
 "ACE_surgicalKit",
 "ACE_NVG_Gen4",
 "G_Bandanna_aviator",
 "ACE_bloodIV_500",
 "G_Tactical_Clear",
 "G_Aviator",
 "ACE_bloodIV",
 "Laserdesignator",
 "ACE_key_lockpick",
 "rhs_googles_orange",
 "MineDetector",
 "ACE_MapTools",
 "ACE_epinephrine",
 "rhsusf_opscore_04_ocp",
 "ACE_personalAidKit",
 "FirstAidKit",
 "ACE_atropine",
 "ACE_EarPlugs",
 "rhs_balaclava",
 "G_Balaclava_lowprofile",
 "ACE_plasmaIV_250",
 "ItemCompass",
 "ACE_microDAGR",
 "ACE_bloodIV_250",
 "ACE_elasticBandage",
 "ACE_Kestrel4500",
 "ACE_Clacker",
 "rhsusf_opscore_01_tan",
 "rhsusf_Bowman",
 "ACE_salineIV_500",
 "ACE_packingBandage",
 "ACE_RangeTable",
 "rhsusf_opscore_02_tan",
 "ACE_M26_Clacker",
 "ItemMap",
 "ACE_fieldDressing",
 "ACE_IR_Strobe_Item",
 "ACE_ATragMX",
 "G_Bandanna_shades",
 "Rangefinder",
 "rhs_googles_clear",
 "G_Balaclava_blk",
 "G_Balaclava_combat",
 "ACE_Cellphone",
 "V_TacVestIR_blk",
 "V_RebreatherIR",
 "rhsusf_spc",
 "ACE_microDAGR",
 "V_Press_F",
 "V_PlateCarrierGL_rgr"
];
_magazines = [
"RH_15Rnd_9x19_M9",
"rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer",
"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
"rhsusf_20Rnd_762x51_m118_special_Mag",
"rhsusf_20Rnd_762x51_m993_Mag",
"rhsusf_20Rnd_762x51_m62_Mag",
"rhs_200rnd_556x45_M_SAW",
"rhs_200rnd_556x45_B_SAW",
"rhs_200rnd_556x45_T_SAW",
"rhsusf_50Rnd_762x51",
"rhsusf_100Rnd_762x51",
"rhsusf_50Rnd_762x51_m62_tracer",
"SmokeShellBlue",
"SmokeShellGreen",
"SmokeShellOrange",
"SmokeShellPurple",
"SmokeShellRed",
"SmokeShellYellow",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"rhs_mag_m67",
"SmokeShell",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"rhsusf_ANPVS_15",
"ACE_VectorDay",
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_IR_Strobe_Item",
"ACE_EarPlugs",
"ACE_DefusalKit",
"ACE_Flashlight_XL50",
"ACE_MapTools",
"ACE_wirecutter",
"ToolKit",
"tf_anprc148jem_2",
"ItemMicroDAGR",
"RH_compM2",
"RH_ta31rco_2D",
"rhs_mag_smaw_HEDP",
"RH_leu_mk4",
"rhsusf_m112x4_mag",

"rhs_mag_m576",
 "rhsusf_mag_6Rnd_M441_HE",
  "rhs_mag_m714_White",
  "rhs_mag_M433_HEDP",
  "rhs_mag_an_m8hc",
  "B_IR_Grenade",
  "rhs_mag_m4009",
  "rhs_mag_m18_yellow",
  "rhs_mag_30Rnd_556x45_M200_Stanag",
  "rhsusf_100Rnd_556x45_soft_pouch",
  "rhs_mag_m18_green",
  "rhsusf_100Rnd_762x51_m993",
  "9Rnd_45ACP_Mag",
  "ACE_HandFlare_White",
  "rhs_mag_30Rnd_556x45_Mk318_Stanag",
  "rhs_mag_m69",
  "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow",
  "FlareGreen_F",
  "rhs_mag_m713_Red",
  "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Green",
  "rhsusf_mag_6Rnd_M714_white",
  "rhs_mag_m715_Green",
  "rhs_mag_m7a3_cs",
  "rhs_mag_m18_red",
  "SmokeShellOrange",
  "SmokeShellGreen",
  "FlareYellow_F",
  "rhs_mag_m662_red",
  "rhs_mag_mk84",
  "SmokeShellPurple",
  "rhs_mag_M585_white",
  "SmokeShellBlue",
  "rhsusf_100Rnd_762x51_m80a1epr",
  "ACE_HandFlare_Red",
  "ACE_HandFlare_Yellow",
  "FlareWhite_F",
  "rhsusf_20Rnd_762x51_m118_special_Mag",
  "rhsusf_5Rnd_300winmag_xm2010",
  "rhs_mine_M19_mag",
  "rhsusf_mag_15Rnd_9x19_JHP",
  "rhsusf_100Rnd_762x51",
  "rhsusf_mag_17Rnd_9x19_FMJ",
  "rhs_mag_m661_green",
  "SmokeShell",
  "rhsusf_20Rnd_762x51_m993_Mag",
  "FlareRed_F",
  "ACE_HandFlare_Green",
  "rhsusf_100Rnd_556x45_M200_soft_pouch",
  "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red",
  "I_IR_Grenade",
  "rhsusf_mag_6Rnd_M576_Buckshot",
  "rhs_mag_m18_purple",
  "rhsusf_mag_6Rnd_M781_Practice",
  "SLAMDirectionalMine_Wire_Mag",
  "Laserbatteries",
  "rhs_mag_30Rnd_556x45_M855A1_Stanag",
  "rhs_mag_30Rnd_556x45_Mk262_Stanag",
  "ACE_M84",
  "rhs_mag_m716_yellow",
  "rhsusf_200Rnd_556x45_soft_pouch",
  "rhsusf_mag_17Rnd_9x19_JHP",
  "rhsusf_mag_15Rnd_9x19_FMJ",
  "rhsusf_mag_6Rnd_M433_HEDP",
  "DemoCharge_Remote_Mag",
  "rhs_mag_an_m14_th3",
  "rhs_mag_M441_HE"




];
_backpacks = [ //includes radios/static weapons
"rhsusf_assault_eagleaiii_ucp",
"B_Parachute",
"tf_anprc155",
"B_UAV_01_backpack_F",
"B_Carryall_oli",
"B_FieldPack_cbr",
"B_Carryall_khk",
"B_Parachute",
"ACE_NonSteerableParachute",
"B_Carryall_mcamo",
"rhsusf_assault_eagleaiii_coy",
"B_FieldPack_oli"
];






//------------------------DO NOT TOUCH----------------------------------------------------
_crate = _this;


_crate AddAction ["<t color=""#4DB0E2"">" +"Special Forces Crate", "","",6];


[_crate,_weapons,{true}] call BIS_fnc_addVirtualWeaponCargo;
[_crate,_items,{true}] call BIS_fnc_addVirtualItemCargo;
[_crate,_magazines,{true}] call BIS_fnc_addVirtualMagazineCargo;
[_crate,_backpacks,{true}] call BIS_fnc_addVirtualBackpackCargo;